# Generated by Django 2.0 on 2018-03-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tEquipment',
            fields=[
                ('EquipSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='장비코드')),
                ('EquipNo', models.CharField(max_length=20, null=True, verbose_name='장비번호')),
                ('EquipName', models.CharField(max_length=20, null=True, verbose_name='장비명')),
            ],
            options={
                'verbose_name': '장비',
                'verbose_name_plural': '장비',
            },
        ),
        migrations.CreateModel(
            name='tMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SenseDT', models.CharField(max_length=20, null=True, verbose_name='기록일시')),
                ('EquipNo', models.CharField(max_length=20, null=True, verbose_name='장비번호')),
                ('SensorNo', models.CharField(max_length=20, null=True, verbose_name='센서번호')),
                ('Value', models.CharField(max_length=20, null=True, verbose_name='값')),
                ('RcvDT', models.DateTimeField(max_length=20, null=True, verbose_name='수신일시')),
                ('RcvStatus', models.IntegerField(verbose_name='수신상태')),
            ],
            options={
                'verbose_name': '측정',
                'verbose_name_plural': '측정',
            },
        ),
        migrations.CreateModel(
            name='tSensor',
            fields=[
                ('SensorSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='센서코드')),
                ('SensorNo', models.CharField(max_length=20, null=True, verbose_name='센서번호')),
                ('SensorName', models.CharField(max_length=20, null=True, verbose_name='센서명')),
                ('EquipSeq', models.IntegerField(null=True, verbose_name='장착장비코드')),
            ],
            options={
                'verbose_name': '센서',
                'verbose_name_plural': '센서',
            },
        ),
    ]
