# Generated by Django 2.0 on 2018-03-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IOTApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmeasure',
            old_name='SenseDT',
            new_name='MeasureDT',
        ),
    ]
