# Generated by Django 2.0.3 on 2018-04-14 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IOTApp', '0003_auto_20180306_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='tDept',
            fields=[
                ('DeptSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='부서코드')),
                ('DeptNo', models.CharField(max_length=20, null=True, verbose_name='부서번호')),
                ('DeptName', models.CharField(max_length=20, null=True, verbose_name='부서명')),
            ],
            options={
                'verbose_name': '부서',
                'verbose_name_plural': '01.부서',
            },
        ),
        migrations.CreateModel(
            name='tEmp',
            fields=[
                ('EmpSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='사원코드')),
                ('EmpNo', models.CharField(max_length=20, null=True, verbose_name='사원번호')),
                ('EmpName', models.CharField(max_length=20, null=True, verbose_name='사원명')),
            ],
            options={
                'verbose_name': '사원',
                'verbose_name_plural': '02.사원',
            },
        ),
        migrations.CreateModel(
            name='tRouting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PEquipIP', models.CharField(max_length=20, null=True, verbose_name='부모IP')),
                ('CEquipIP', models.CharField(max_length=20, null=True, verbose_name='자식IP')),
            ],
            options={
                'verbose_name': '라우팅',
                'verbose_name_plural': '라우팅',
            },
        ),
        migrations.AlterModelOptions(
            name='tequipment',
            options={'verbose_name': '장비', 'verbose_name_plural': '03.장비'},
        ),
        migrations.AlterModelOptions(
            name='tsensor',
            options={'verbose_name': '센서', 'verbose_name_plural': '04.센서'},
        ),
        migrations.AddField(
            model_name='tequipment',
            name='EquipType',
            field=models.CharField(max_length=20, null=True, verbose_name='장비부호'),
        ),
        migrations.AddField(
            model_name='tequipment',
            name='Remark',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='tsensor',
            name='EquipSeq',
            field=models.ForeignKey(blank=True, db_column='EquipSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTApp.tEquipment', verbose_name='장착장비'),
        ),
        migrations.AddField(
            model_name='trouting',
            name='CEquipSeq',
            field=models.ForeignKey(blank=True, db_column='CEquipSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTApp.tEquipment', verbose_name='자식장비'),
        ),
        migrations.AddField(
            model_name='trouting',
            name='PEquipSeq',
            field=models.ForeignKey(blank=True, db_column='PEquipSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTApp.tEquipment', verbose_name='부모장비'),
        ),
        migrations.AddField(
            model_name='tequipment',
            name='DeptSeq',
            field=models.ForeignKey(blank=True, db_column='DeptSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTApp.tDept', verbose_name='사용부서'),
        ),
    ]
