# Generated by Django 2.0.3 on 2018-04-14 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IOTApp', '0004_auto_20180414_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='tDCode',
            fields=[
                ('DCodeSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='D코드내부코드')),
                ('DCodeName', models.CharField(blank=True, max_length=50, null=True, verbose_name='D코드명')),
                ('Remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='비고')),
                ('RegDT', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='등록일시')),
                ('UptDT', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '공통코드D',
                'verbose_name_plural': '11.공통코드D',
            },
        ),
        migrations.CreateModel(
            name='tMCode',
            fields=[
                ('MCodeSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='M코드내부코드')),
                ('MCodeNo', models.CharField(blank=True, max_length=20, null=True, verbose_name='M코드번호')),
                ('MCodeName', models.CharField(blank=True, max_length=20, null=True, verbose_name='M코드명')),
                ('Remark', models.CharField(blank=True, max_length=20, null=True, verbose_name='비고')),
                ('RegDT', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='등록일시')),
                ('UptDT', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='수정일시')),
                ('RegUserSeq', models.ForeignKey(db_column='RegUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('UptUserSeq', models.ForeignKey(db_column='UptUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '공통코드M',
                'verbose_name_plural': '10.공통코드M',
            },
        ),
        migrations.AlterModelOptions(
            name='trouting',
            options={'verbose_name': '라우팅', 'verbose_name_plural': '05.라우팅'},
        ),
        migrations.AlterField(
            model_name='tequipment',
            name='EquipType',
            field=models.ForeignKey(blank=True, db_column='EquipType', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTApp.tMCode', verbose_name='사용부서'),
        ),
        migrations.AddField(
            model_name='tdcode',
            name='MCodeSeq',
            field=models.ForeignKey(db_column='MCodeSeq', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='IOTApp.tMCode', verbose_name='M코드'),
        ),
        migrations.AddField(
            model_name='tdcode',
            name='RegUserSeq',
            field=models.ForeignKey(db_column='RegUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='tdcode',
            name='UptUserSeq',
            field=models.ForeignKey(db_column='UptUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
    ]
