# Generated by Django 2.0.3 on 2018-04-14 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IOTApp', '0005_auto_20180414_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='tequipment',
            name='RegDT',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='등록일시'),
        ),
        migrations.AddField(
            model_name='tequipment',
            name='RegUserSeq',
            field=models.ForeignKey(db_column='RegUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='tequipment',
            name='UptDT',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='수정일시'),
        ),
        migrations.AddField(
            model_name='tequipment',
            name='UptUserSeq',
            field=models.ForeignKey(db_column='UptUserSeq', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AlterField(
            model_name='tequipment',
            name='EquipType',
            field=models.ForeignKey(blank=True, db_column='EquipType', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTApp.tDCode', verbose_name='장비종류'),
        ),
    ]
