# Generated by Django 2.0.3 on 2018-05-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTApp', '0006_auto_20180414_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdcode',
            name='MCodeSeq',
        ),
        migrations.RemoveField(
            model_name='tdcode',
            name='RegUserSeq',
        ),
        migrations.RemoveField(
            model_name='tdcode',
            name='UptUserSeq',
        ),
        migrations.DeleteModel(
            name='tDept',
        ),
        migrations.DeleteModel(
            name='tEmp',
        ),
        migrations.RemoveField(
            model_name='tequipment',
            name='DeptSeq',
        ),
        migrations.RemoveField(
            model_name='tequipment',
            name='EquipType',
        ),
        migrations.RemoveField(
            model_name='tequipment',
            name='RegUserSeq',
        ),
        migrations.RemoveField(
            model_name='tequipment',
            name='UptUserSeq',
        ),
        migrations.RemoveField(
            model_name='tmcode',
            name='RegUserSeq',
        ),
        migrations.RemoveField(
            model_name='tmcode',
            name='UptUserSeq',
        ),
        migrations.RemoveField(
            model_name='trouting',
            name='CEquipSeq',
        ),
        migrations.RemoveField(
            model_name='trouting',
            name='PEquipSeq',
        ),
        migrations.RemoveField(
            model_name='tsensor',
            name='EquipSeq',
        ),
        migrations.AlterModelOptions(
            name='tmeasure',
            options={'verbose_name': 'Measure', 'verbose_name_plural': 'Measure'},
        ),
        migrations.RemoveField(
            model_name='tmeasure',
            name='ValueCd',
        ),
        migrations.AlterField(
            model_name='tmeasure',
            name='EquipNo',
            field=models.CharField(max_length=20, null=True, verbose_name='Controller No'),
        ),
        migrations.AlterField(
            model_name='tmeasure',
            name='MeasureDT',
            field=models.CharField(max_length=20, null=True, verbose_name='Measure DateTime'),
        ),
        migrations.AlterField(
            model_name='tmeasure',
            name='RcvDT',
            field=models.CharField(max_length=20, null=True, verbose_name='Receive DateTime'),
        ),
        migrations.AlterField(
            model_name='tmeasure',
            name='SensorNo',
            field=models.CharField(max_length=20, null=True, verbose_name='Sensor No'),
        ),
        migrations.AlterField(
            model_name='tmeasure',
            name='Value',
            field=models.CharField(max_length=1000, null=True, verbose_name='Measure value'),
        ),
        migrations.DeleteModel(
            name='tDCode',
        ),
        migrations.DeleteModel(
            name='tEquipment',
        ),
        migrations.DeleteModel(
            name='tMCode',
        ),
        migrations.DeleteModel(
            name='tRouting',
        ),
        migrations.DeleteModel(
            name='tSensor',
        ),
    ]
