# Generated by Django 2.0.3 on 2018-05-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTApp', '0007_auto_20180511_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmeasure',
            name='SndDT',
            field=models.CharField(max_length=20, null=True, verbose_name='Send DateTime'),
        ),
    ]
