# Generated by Django 2.0.5 on 2018-05-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTApp', '0008_tmeasure_snddt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmeasure',
            name='ControllerNo',
            field=models.CharField(max_length=20, null=True, verbose_name='ControllerNo No'),
        ),
        migrations.AlterField(
            model_name='tmeasure',
            name='MeasureDT',
            field=models.CharField(max_length=20, null=True, verbose_name='Measured DateTime'),
        ),
        migrations.AlterField(
            model_name='tmeasure',
            name='RcvDT',
            field=models.CharField(max_length=20, null=True, verbose_name='Received DateTime'),
        ),
        migrations.AlterField(
            model_name='tmeasure',
            name='Value',
            field=models.CharField(max_length=1000, null=True, verbose_name='Values'),
        ),
    ]
