# Generated by Django 2.0.5 on 2018-05-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTApp', '0010_tdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdevice',
            name='ipaddress',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='tdevice',
            name='DeviceName',
            field=models.CharField(max_length=40, null=True, verbose_name='Device Name'),
        ),
        migrations.AlterField(
            model_name='tdevice',
            name='DeviceType',
            field=models.CharField(choices=[('1', 'sensor'), ('2', 'controller'), ('3', 'gateway'), ('4', 'server')], max_length=1, null=True, verbose_name='Device Type'),
        ),
    ]
