# Generated by Django 2.0.5 on 2018-05-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTApp', '0011_auto_20180523_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdevice',
            name='ipaddress',
        ),
        migrations.AddField(
            model_name='tdevice',
            name='IPaddress',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IP address'),
        ),
    ]
