# Generated by Django 2.0.5 on 2018-05-23 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IOTApp', '0012_auto_20180523_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='tRouting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CDeviceSeq', models.ForeignKey(blank=True, db_column='CDeviceSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTApp.tDevice', verbose_name='Child Device')),
                ('PDeviceSeq', models.ForeignKey(blank=True, db_column='PDeviceSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTApp.tDevice', verbose_name='Parent Device')),
            ],
            options={
                'verbose_name': 'Routing',
                'verbose_name_plural': 'Routing',
            },
        ),
        migrations.AlterField(
            model_name='tmeasure',
            name='EquipNo',
            field=models.CharField(max_length=20, null=True, verbose_name='Equipment No'),
        ),
    ]
