# Generated by Django 2.0.5 on 2018-05-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IOTApp', '0013_auto_20180523_1622'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tdevice',
            unique_together={('DeviceNo',)},
        ),
        migrations.AlterUniqueTogether(
            name='tmeasure',
            unique_together={('EquipNo', 'ControllerNo', 'SensorNo')},
        ),
        migrations.AlterUniqueTogether(
            name='trouting',
            unique_together={('PDeviceSeq', 'CDeviceSeq')},
        ),
    ]
