# Generated by Django 2.0.5 on 2018-06-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTApp', '0014_auto_20180523_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmeasure',
            name='OrderCd',
            field=models.CharField(max_length=1000, null=True, verbose_name='Order code'),
        ),
    ]
