# Generated by Django 2.0.5 on 2018-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTApp', '0015_tmeasure_ordercd'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdevice',
            name='StautsCd',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Status code'),
        ),
    ]
