# Generated by Django 2.0.7 on 2018-07-24 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IOTApp', '0018_auto_20180630_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='tMyServerinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerName', models.CharField(max_length=40, null=True, verbose_name='Server Name')),
                ('IPaddress', models.CharField(blank=True, max_length=30, null=True, verbose_name='My IP address:port')),
                ('DatastoreIPaddress', models.CharField(blank=True, max_length=30, null=True, verbose_name='Datastore IP address:port')),
                ('DeviceSeq', models.ForeignKey(blank=True, db_column='DeviceSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTApp.tDevice', verbose_name='Device Info')),
            ],
            options={
                'verbose_name': 'MyServerinfo',
                'verbose_name_plural': 'MyServerinfo',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tmyserverinfo',
            unique_together={('ServerName', 'DeviceSeq')},
        ),
    ]
